"use client";

import { useState } from "react";
import { StudyFormData } from "@/types";
import { createClient } from "@/lib/supabase-client";
import {
  Sparkles,
  Save,
  CheckCircle2,
  Loader2,
  BookOpen,
  Calendar,
  X,
} from "lucide-react";

interface PlanPreviewProps {
  plan: string;
  formData: StudyFormData;
  onSaved: () => void;
  onClose: () => void;
}

export default function PlanPreview({
  plan,
  formData,
  onSaved,
  onClose,
}: PlanPreviewProps) {
  const [saving, setSaving] = useState(false);
  const [saved, setSaved] = useState(false);
  const [error, setError] = useState("");

  const handleSave = async () => {
    setSaving(true);
    setError("");
    try {
      const supabase = createClient();
      const { error: dbError } = await supabase.from("study_plans").insert({
        subject: formData.subject,
        topics: formData.topics,
        exam_date: formData.examDate,
        plan_content: plan,
      });

      if (dbError) throw dbError;

      setSaved(true);
      setTimeout(() => {
        onSaved();
      }, 1200);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : "Failed to save plan.";
      setError(msg);
    } finally {
      setSaving(false);
    }
  };

  // Render markdown-like content
  const renderContent = (content: string) => {
    const lines = content.split("\n");
    return lines.map((line, i) => {
      if (line.startsWith("## ")) {
        return (
          <h3 key={i} className="text-lg font-bold text-indigo-700 mt-5 mb-2 flex items-center gap-2">
            {line.replace("## ", "")}
          </h3>
        );
      }
      if (line.startsWith("### ")) {
        return (
          <h4 key={i} className="text-base font-semibold text-gray-800 mt-4 mb-1">
            {line.replace("### ", "")}
          </h4>
        );
      }
      if (line.startsWith("- ") || line.startsWith("• ")) {
        const text = line.replace(/^[-•] /, "").replace(/\*\*(.*?)\*\*/g, "$1");
        return (
          <li key={i} className="text-sm text-gray-700 ml-5 list-disc leading-relaxed">
            {text}
          </li>
        );
      }
      if (line.trim() === "") return <div key={i} className="h-1.5" />;
      
      const formatted = line.replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>");
      return (
        <p
          key={i}
          className="text-sm text-gray-700 leading-relaxed"
          dangerouslySetInnerHTML={{ __html: formatted }}
        />
      );
    });
  };

  return (
    <div className="bg-white/80 backdrop-blur-sm rounded-2xl shadow-xl border border-white/50 overflow-hidden">
      {/* Header */}
      <div className="bg-gradient-to-r from-indigo-600 to-purple-600 p-6">
        <div className="flex items-start justify-between">
          <div className="flex items-center gap-3">
            <div className="p-2 bg-white/20 rounded-xl">
              <Sparkles className="w-6 h-6 text-white" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-white">Your Study Plan</h2>
              <p className="text-indigo-200 text-sm">Generated by PrepWise AI</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 hover:bg-white/20 rounded-xl transition-colors text-white/70 hover:text-white"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Meta badges */}
        <div className="flex flex-wrap gap-2 mt-4">
          <span className="flex items-center gap-1.5 bg-white/20 text-white text-xs px-3 py-1.5 rounded-full font-medium">
            <BookOpen className="w-3.5 h-3.5" />
            {formData.subject}
          </span>
          <span className="flex items-center gap-1.5 bg-white/20 text-white text-xs px-3 py-1.5 rounded-full font-medium">
            <Calendar className="w-3.5 h-3.5" />
            Exam: {new Date(formData.examDate).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}
          </span>
        </div>
      </div>

      {/* Plan Content */}
      <div className="p-6 max-h-[50vh] overflow-y-auto">
        <div className="prose prose-sm max-w-none">
          {renderContent(plan)}
        </div>
      </div>

      {/* Actions */}
      <div className="border-t border-gray-100 p-5 bg-gray-50/50 flex flex-col sm:flex-row items-center gap-3">
        {error && (
          <p className="text-sm text-red-500 flex-1">⚠️ {error}</p>
        )}

        <div className="flex items-center gap-3 ml-auto">
          <button
            onClick={onClose}
            className="px-4 py-2.5 text-sm font-medium text-gray-600 hover:text-gray-800 hover:bg-gray-200 rounded-xl transition-all duration-150"
          >
            Discard
          </button>
          <button
            onClick={handleSave}
            disabled={saving || saved}
            className="flex items-center gap-2 px-5 py-2.5 bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-700 hover:to-purple-700 disabled:opacity-70 text-white text-sm font-semibold rounded-xl transition-all duration-200 shadow-md hover:shadow-lg hover:-translate-y-0.5 active:translate-y-0"
          >
            {saved ? (
              <>
                <CheckCircle2 className="w-4 h-4" />
                Saved!
              </>
            ) : saving ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                Saving...
              </>
            ) : (
              <>
                <Save className="w-4 h-4" />
                Save Plan
              </>
            )}
          </button>
        </div>
      </div>
    </div>
  );
}
